kj-gitbot: PKGBUILD

diff --git a/coreutils-uutils/PKGBUILD b/coreutils-uutils/PKGBUILD
--- a/coreutils-uutils/PKGBUILD
+++ b/coreutils-uutils/PKGBUILD
@@ -77,6 +77,14 @@ package() {
   # additional cleanup
   rm $pkgdir/usr/share/bash-completion/completions/*
   rm $pkgdir/usr/share/man/man1/{groups.1,hostname.1,install.1,kill.1,more.1,uptime.1}
+
+  # create dummy shell scripts for chcon and runcon
+  install -m 755 <(echo "#!/bin/sh
+echo \"error: chcon not built with coreutils-uutils package\"
+exit 1") $pkgdir/usr/bin/chcon
+  install -m 755 <(echo "#!/bin/sh
+echo \"error: runcon not built with coreutils-uutils package\"
+exit 1") $pkgdir/usr/bin/runcon
 }
 
 # vim: ts=2 sw=2 et:
